services:
  php:
    build:
      context: .
    volumes:
      - .:/app
      - ${HOME}/.composer

  setup:
    build:
      context: .
    profiles:
      - setup
    entrypoint: ["composer", "install"]
    volumes:
      - .:/app
      - ${HOME}/.composer
